### ISSUE TITLE
Implement finding bookmark by tag into DAO & service

### ISSUE THREAD

**Issue by cxcorp** [pohina-oy/vinkkisofta#34]
by tag **s**, e.g. `findByTags(Tag[])` or whatever Collection or List or Set

**Comment by l-y-l** [comment]
Implemented methods for searching bookmarks by tags into service `getBookmarksByTags(String)` and Dao `findByTagSet(Set<Tag>)` with assumed methods and tagDao as well as private helper methods for parsing tag string to `Set<Tag>`. Missing tests and restructuring according to dependencies.

**Comment by l-y-l** [comment]
blocked by #28, shared service methods with #37
