### ISSUE TITLE
UserDao and an in-memory implementation

### ISSUE THREAD

**Issue by cxcorp** [pohina-oy/vinkkisofta#70]
probably

```
User findByGithubId(int id);
User findById(String id);
void add(User user);
```

for extensibility, keep in mind that in this sprint: will need to be able to associate users to bookmarks

blocked by #71

**Comment by l-y-l** [comment]
Since there is a one-to-many relationship between users and bookmarks (each bookmark can only have one creator), I think BookmarkDao will handle the association.
